### ISSUE TITLE
[Trainings] Add defdev.eu secure development trainings

### ISSUE THREAD

**Issue by david3107** [UnityTech/unity-ssdlc#5]
Hello,

as part of the possible trainings that developers can get to increase their secure development knowledge I would like to add the following list of trainings from defdev.eu:

- [Java](https://c.defdev.eu/code/java)
- [JavaScript](https://c.defdev.eu/code/js)
- [Android](https://c.defdev.eu/code/android)
- [iOS](https://c.defdev.eu/code/ios)
- [.NET](https://c.defdev.eu/code/dotnet)
- [C/Cpp](https://c.defdev.eu/code/cpp)
- [Web Application Security](https://c.defdev.eu/code/webapps-all)
- [Mobile Testing Automation](https://c.defdev.eu/test/mobile-testing-automation)
- [Security test automation in CI/CD pipelines
](https://c.defdev.eu/test/cicd)
- [Burp for developers](https://c.defdev.eu/test/burp)

Cheers,
Davide

**Comment by brandon-unity** [comment]
We are currently not looking to just hosting a list of links to external content, though I have been considering this. _(Particularly given the rich assets produced and shared by OWASP)._  This breaks the idea of simply being able to clone the whole repo and having all the resources you need - hence my hesitation.

However, your content looks to be part of a product offering from a company.  We currently have no plans to provide recommendations or endorsements for commercial training services.

Thanks for the recommendations - we'd be more than happy to discuss receiving contributions according to our contribution guidelines though :) 
-Brandon
